UPDATE OPENMM_MOVIES SET NAME = ?, DISPLAY_NAME = ?, DESCRIPTION = ?, GENRE = ?,
	IMDB_NUMBER = ?, RTID_NUMBER = ?, MPAA_RATING = ?, RATING = ?, RUNTIME = ?,
	RELEASE_DATE = ?, YEAR = ?, POSTER_URL = ? WHERE MOVIE_ID = ?