SELECT LEFT( UPPER( OPENMM_MOVIES.NAME ), 1 ) PREFIX,
	( SELECT COUNT(*) FROM OPENMM_MOVIES TBL_A
		WHERE LEFT( UPPER( TBL_A.NAME ), 1 ) = LEFT( UPPER( OPENMM_MOVIES.NAME ), 1 )
	) NUM_MOVIES,
	( SELECT COUNT(*) FROM OPENMM_MOVIES TBL_B
		WHERE LEFT( UPPER( TBL_B.NAME ), 1 ) = LEFT( UPPER( OPENMM_MOVIES.NAME ), 1 )
			AND (
				SELECT COUNT( * ) FROM OPENMM_LINKS
					WHERE OPENMM_LINKS.TYPE_CODE = 'M'
						AND OPENMM_LINKS.REF_ID = TBL_B.MOVIE_ID
						AND OPENMM_LINKS.AVAILABLE = 'Y'
			) > 0
	) NUM_MOVIES_AVAIL
	FROM OPENMM_MOVIES
	GROUP BY PREFIX
	ORDER BY PREFIX
