UPDATE OPENMM_SHOW_EPISODES SET SEASON_ID = ?, TVDB_ID = ?, NAME = ?, EPNUM = ?, DVD_EPNUM = ?,
	SCREENSHOT_PATH = ?, DESCRIPTION = ?, AIR_DATE = ?, RATING = ?, LAST_WATCHED = ?,
	WATCH_COUNT = ? WHERE EPISODE_ID = ?