SELECT SEASON_ID, (
	SELECT COUNT( * ) FROM OPENMM_SHOW_EPISODES
		WHERE OPENMM_SHOW_EPISODES.SEASON_ID = OPENMM_SHOW_SEASONS.SEASON_ID
		AND ( SELECT COUNT(*) FROM OPENMM_LINKS WHERE AVAILABLE = 'Y' AND TYPE_CODE = 'S' AND REF_ID = OPENMM_SHOW_EPISODES.EPISODE_ID ) > 0
	) NUM_EP_AVAILABLE,
	( SELECT COUNT( * ) FROM OPENMM_SHOW_EPISODES
		WHERE OPENMM_SHOW_EPISODES.SEASON_ID = OPENMM_SHOW_SEASONS.SEASON_ID
	) NUM_EP
	FROM OPENMM_SHOW_SEASONS WHERE SHOW_ID = ?